### ISSUE TITLE
Broken Characters in Help File

### ISSUE THREAD

**Issue by Tartarus6** [Tartarus6/Tarsweeper#6]
Not sure where the fault lies, but when updating the 'minesweeper.hlp' file through VSCode the special CP437 characters (such as ƒ) broke. They now render as several characters, neither of which is correct.

The issue was fine when doing it through notepad++ and FTP. So it's probably either git or VSCode that's to blame.

Notepad++ with FTP:
![image](https://github.com/Tartarus6/Tarsweeper/assets/88263600/d32fd014-bc25-4a7b-85cc-b6f7356916a0)
![image](https://github.com/Tartarus6/Tarsweeper/assets/88263600/8f41947e-90c1-494f-9917-f507d3373aab)

VSCode with git:
![image](https://github.com/Tartarus6/Tarsweeper/assets/88263600/c7d627b3-58e0-4344-aada-49f28dce248c)
![image](https://github.com/Tartarus6/Tarsweeper/assets/88263600/cdcdb7e1-f547-464b-86e6-0ddc37fc6929)

*Note: the asterisks were removed between the two intentionally, its not a symptom of the bug.*

**Comment by greenturtle537** [comment]
Fixed this issue. You'll need to use an editor with DOS437 or MS437 compliant character encoding. Standard unicode editors and fonts will not work for editing. Copying the unicode version of these character from other sources will also break. Recommended to use EditPad, Gnome Editor, or Nano for the time being. Feel free to reopen if you find a patch for VSC and Notepad++.
